version: "3.7"

services:
    # image project
    app:
        container_name: template-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: template/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        container_name: template-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    mysql:
        container_name: template-mysql
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: template_db
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: template_user
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel
           
    # db postgres   
    postgres:
      container_name: template-pg
      image: postgres:14.2-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: 123456
      ports:
        - "5432:5432"

    # queue
    queue:
        container_name: template-queue
        image: template/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel

    # redis
    redis:
        container_name: template-redis
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge
